serpent_gazebo:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20
  serpent_joint_1_position_controller:
    type: position_controllers/JointPositionController
    joint: serpent_joint_1
    pid: {p: 50.0, i: 5.0, d: 5.0}
 

