serpent_gazebo:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20
  serpent_joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: serpent_joint_1
    pid: {p: 100.0, i: 0.01, d: 10.0}

