modulessai:
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

serpent_main_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: serpent_main_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}
